ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.akviklabs.online
CATALOGUE_HOST: catalogue-{{ env }}.akviklabs.online
REDIS_HOST: redis-{{ env }}.akviklabs.online
USER_HOST: user-{{ env }}.akviklabs.online
CART_HOST: cart-{{ env }}.akviklabs.online
MYSQL_HOST: mysql-{{ env }}.akviklabs.online
SHIPPING_HOST: shipping-{{ env }}.akviklabs.online
RABBITMQ_HOST: rabbitmq-{{ env }}.akviklabs.online
PAYMENT_HOST: payment-{{ env }}.akviklabs.online